export const DEFAULT_DAY_NUMBER = 14;

export const DEFAULT_SUBTRACT_DAY_NUMBER = 2;

export const DEFAULT_STEP_DAY_NUMBER = 14;

export const DEFAULT_COLUMN_WIDTH = 50;

export const DEFAULT_TITLE_ROW_HEIGHT = 45;

export const DEFAULT_DATE_ROW_HEIGHT = 65;
